name: JobPortal CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container   # ✅ This fixes the error
          buildkitd-flags: --debug

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚙️ Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Backend/JobPortal/JobPortal.API/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jobportal-backend:latest
            ghcr.io/${{ github.repository_owner }}/jobportal-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: ⚙️ Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jobportal-frontend:latest
            ghcr.io/${{ github.repository_owner }}/jobportal-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
